apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.postgres.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: {{ .Values.postgres.name }}
  namespace: {{ .Values.postgres.name }}
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.postgres.name }}
  name: postgres-volume
  labels:
    type: local
    app: {{ .Values.postgres.name }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.postgres.name }}
  name: postgres-volume-claim
  labels:
    app: {{ .Values.postgres.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.postgres.name }}
  name: {{ .Values.postgres.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: 'postgres:14'
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.postgres.name }}
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: {{ .Values.postgres.name }}
